#!/bin/bash
if [ "$EUID" -ne 0 ]
then echo "Please run as root"
	exit
fi
SSIDS=$(/sbin/iwlist wlan0 scan | grep "ESSID")
while read -r line; do
	line=${line#*'"'}
	line=${line%'"'*}
    echo $line
done <<< "$SSIDS"
