#!/bin/bash
if [ "$EUID" -ne 0 ]
then echo "Please run as root"
	exit
fi

if (( $# != 1 )); then
	echo "usage: $0 <ssid>"
	exit 1
fi

psk="$(cat /etc/wpa_supplicant/wpa_supplicant.conf | grep -A 1 "ssid=\"$1\"" | grep "#psk=" )"
psk=${psk#*'"'}
psk=${psk%'"'*}
echo -n "$psk"
