#!/bin/bash
if [ "$EUID" -ne 0 ]
then echo "Please run as root"
	exit
fi

NUM=60
for i in $(seq 1 $NUM); do
	ping -c 1 -W 1 $REMOTE_IP > /dev/null && break
	sleep 1
done
[ $i -lt $NUM ] && /usr/bin/autossh -i "$KEY_LOCATION" -N -R 127.0.0.1:$REMOTE_PORT:localhost:80 raveberry@$REMOTE_IP
